### ISSUE TITLE
Fit to page?

### ISSUE THREAD

**Issue by wootwoot1234** [BafS/Gutenberg#15]
Is there a way to make some content fit to a page?  I'm using the `page-break-after` class but having an issue where sometimes some of the content is too long and it rolls over onto a new page.  Is there a way to shrink or cut off the content so that it doesn't create another page?

**Comment by BafS** [comment]
What kind of content is it ? If it's text, they will be 3 lines left at the top/bottom of a page.
https://github.com/BafS/Gutenberg/blob/master/scss/_pagination.scss#L21

For the moment it's hardcoded but I will probably create a variable to change that more easily, what do you think ?

**Comment by wootwoot1234** [comment]
Thanks for responding.  It's a simple page layout.  There is a large image that takes up 60% of the page and text below, that takes 40%.  I can't control the amount of text though.  I don't care if the text gets cut off but I just want to make sure that it doesn't create a second page.  How can I do that?

**Comment by BafS** [comment]
Do you have a h1, h2 or h3 ? It's really hard to help you without any source, can you provide a screenshot or some code please ? Thanks.

**Comment by wootwoot1234** [comment]
Thanks for the help.  I think what I'm trying to do isn't possible with css.
