### ISSUE TITLE
Add eyeglass support

### ISSUE THREAD

**Issue by strarsis** [BafS/Gutenberg#17]
It would be nice if eyeglass support is added. PR: https://github.com/BafS/Gutenberg/pull/16

**Comment by BafS** [comment]
Excuse me to reply only now. I don't see any other famous repository that supports eyeglass and I try to keep Gutenberg light if possible. Do you have a lot of projects that support eyeglass ?

**Comment by strarsis** [comment]
List of (important) projects that support eyeglass: https://github.com/sass-eyeglass/eyeglass/issues/170

**Comment by BafS** [comment]
Thanks for your answer, I merged your PR.
