### ISSUE TITLE
Strange width on print

### ISSUE THREAD

**Issue by akalongman** [BafS/Gutenberg#22]
@BafS  thank you for your package.

Could you look at my problem? 

Why is content so narrow there:

![2017-12-08_05 21 23](https://user-images.githubusercontent.com/423050/33746608-ce76f47e-dbd7-11e7-8d94-0c101f49cdaf.jpg)

I have two-columned page layout, `col-sm-3` and `col-sm-9`. First contains menu and has a class `no-print`, on the second I've added class `print-full-width` which has a media print style `width: 100% !important;` but, no result. How can I fix this?

**Comment by akalongman** [comment]
Ok, fixed by creating custom `variables.scss` and setting
```css
$page-padding-left: 0 !default;
$page-padding-right: 0 !default;
```

**Comment by BafS** [comment]
Hi
Sorry for the late reply, I was not available before. Great, you found the solution !
