### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by frederikhors** [BafS/Gutenberg#37]
Is this still maintained?

**Comment by BafS** [comment]
Yes it is, but not actively.

**Comment by frederikhors** [comment]
Can you suggest any actively maintained alternatives?

**Comment by BafS** [comment]
I don't have any out of my mind sorry but if you find some, feel free to list them. On the other hand are you looking for something particular? If you think that something is buggy or missing feel free to open an issue or do a pull request.
I'll update the dependencies soon to make a fresh release.

**Comment by frederikhors** [comment]
Thanks.
