### ISSUE TITLE
Fix dependency versions in releases

### ISSUE THREAD

**Issue by tomm1996** [BafS/Gutenberg#4]
Hello,

it is generally considered a good idea to fix the dependencies of a public npm package to a specific version by not using any prefix in the projects' package.json. `normalize-css 6.0.0` (or when depending on a package vulnerable to security threats, such as a web framework like express to the minor version `normalize-css 6.0.x`).

If you use the default caret (^) character in your package.json, that means that on each `npm update`, npm will install the latest minor release in the current project. Many package authors don't take [semver](http://semver.org/) too seriously, which could mean that a breaking change might be released in a minor version.

So if (just an example, I never had problems with normalize) the author of normalize-css decides that it'd be fancy to set the default background color of anything in the DOM to lime in version `6.9.0`, any CI-Tool would build and deploy that without asking.

Therefore, I'd like to request that little patch to the package.json

Also: 
Could you please be so kind to publish gutenberg-css#3.0.1 on npm? 
I'd be delighted at using the updates in a project I'm about to launch.

More information:
https://blog.nodejitsu.com/package-dependencies-done-right/
http://stackoverflow.com/questions/25432768/change-npm-default-caret-in-package-json

**Comment by BafS** [comment]
Tank you for the feedback !
I published the version 0.3.1, sorry I forgot to do that.

About the semver I don't know, JohnAlbin seems serious about the versions (https://github.com/JohnAlbin/normalize-scss/releases), what do you think ?

**Comment by tomm1996** [comment]
Sorry, I described that issue poorly.

I don't doubt that the normalize-scss-maintainer follows a strict semver policy. That was just an example (I will edit the issue). but many authors do not. I learned that the hard way in quite a few projects.

Because of that, to me, it makes public npm packages more trustworthy if they fix their dependencies when they release a version.

So if you release 0.4.0 and have fixed versions like for example `"gulp": "3.9.1"` instead of `"gulp": "^3.9.1"` in your package-json that will make it more safe to install for me using it in production.

**Comment by BafS** [comment]
I understand you problem but for the moment the maintainer is serious about semver. Other really famous library also use `^` (eg. https://github.com/lodash/lodash/blob/4.17.4/package.json) but I put a tilda `~` for the next version, to only have the patch.
