### ISSUE TITLE
Typo in READ.ME

### ISSUE THREAD

**Issue by LoicLopes** [BafS/Gutenberg#6]
In the section for page break, "Gutenberg provide to way break page, the class page-break will for to break before and page-break-after to break after." should be "Gutenberg provide two ways break page, the class page-break will for to break before and page-break-after to break after."

**Comment by kumarharsh** [comment]
the suggestion is grammatically incorrect. It should be:

Gutenberg provides two ways to break a page: the class `page-break` to break before, and `page-break-after` to break after.

**Comment by LoicLopes** [comment]
You're right, I wrote too fast. Thanks for the correction !

**Comment by BafS** [comment]
Thanks, I will do that as soon as I am on my computer.
